version: 2.0
jobs:
  build:
    working_directory: ~/carambar
    docker:
    - image: circleci/openjdk:8-jdk
    steps:
    - checkout
    - restore_cache:
        keys:
        - carambar-app-{{ checksum "app/build.gradle" }}
        - carambar-app-
    - run:
        name: Execute unit tests
        command: |
          ./gradlew testDebugUnitTest
    - save_cache:
        key: carambar-app-{{ checksum "app/build.gradle" }}
        paths:
        - .gradle
    - store_test_results:
        path: app/build/test-results/testDebugUnitTest